### ISSUE TITLE
Нейминг и расположение файлов 

### ISSUE THREAD

**Issue by lol1pop** [ann-kiy/hotel#2]
Если фаил называется MongoRepo 
и описывает логику репозитория, то его нужно переместить в папку репозитория
и у папок лучше не сокращать имена также как у классов 

repo - repository

**Comment by lol1pop** [comment]
Дальше, вот у тебя есть database_sequences
во первых зачем в названии базы данных database, а во вторых это у тебя коллекция, а не база данных 
в третьих sequences такое себе имя для коллекции стоит подумать

**Comment by lol1pop** [comment]
там же в utils у тебя лежат модели, но при этом у тебя есть папочка модели, если ты их както хочешь разграничить то попробу чтото из разряда 

```
models  --
               |
               users --
                          |
                          User
                          Role
              |
                other--
                           |
                           Model1
                           Model2
```

**Comment by ann-kiy** [comment]
sequences и не будет я быстро поняла что говно идея
